#!/bin/sh
# Renders Traefik file-provider dynamic config from ROUTE_* variables in the env.
# POSIX sh (runs on Alpine/busybox). Output path is arg 1 (default /out/routes.yml).
#
# Route convention in .env (N = 1, 2, 3, ...; must be contiguous starting at 1):
#   ROUTE_1_NAME=example-app                         # unique router/service id
#   ROUTE_1_HOSTS=tinodev.example.com,testcoiff.ex.com # comma-separated hostnames
#   ROUTE_1_SERVICE=http://example-app:3000          # backend url (container or external)
#   ROUTE_1_TLS=true                                   # optional, default true
#   ROUTE_1_ENTRYPOINTS=websecure                      # optional, default websecure
#
# Optional Traefik dashboard:
#   DASHBOARD_HOST=traefik.example.com
#   DASHBOARD_AUTH=admin:$apr1$....   # htpasswd hash (from `htpasswd -nb admin secret`)

set -eu

OUT="${1:-/out/routes.yml}"
TMP="$(mktemp)"

cat > "$TMP" <<'EOF'
# AUTO-GENERATED by scripts/generate-routes.sh — DO NOT EDIT BY HAND.
# Edit ../.env and re-run:  docker compose run --rm route-generator
http:
  routers:
EOF

count=0
n=1
while :; do
  eval "name=\${ROUTE_${n}_NAME:-}"
  [ -z "$name" ] && break

  eval "hosts=\${ROUTE_${n}_HOSTS:-}"
  eval "service=\${ROUTE_${n}_SERVICE:-}"
  eval "tls=\${ROUTE_${n}_TLS:-true}"
  eval "entry=\${ROUTE_${n}_ENTRYPOINTS:-websecure}"

  if [ -z "$hosts" ] || [ -z "$service" ]; then
    echo "ERROR: ROUTE_${n} ($name) is missing HOSTS or SERVICE" >&2
    exit 1
  fi

  # Build:  Host(`a`) || Host(`b`) || ...
  rule=""
  oldIFS=$IFS
  IFS=','
  for h in $hosts; do
    h=$(printf '%s' "$h" | tr -d ' ')
    [ -z "$h" ] && continue
    if [ -z "$rule" ]; then
      rule="Host(\`$h\`)"
    else
      rule="$rule || Host(\`$h\`)"
    fi
  done
  IFS=$oldIFS

  {
    echo "    ${name}:"
    echo "      rule: \"${rule}\""
    echo "      entryPoints: [${entry}]"
    echo "      service: ${name}"
    if [ "$tls" = "true" ]; then
      echo "      tls:"
      echo "        certResolver: le"
    fi
  } >> "$TMP"

  count=$((count + 1))
  n=$((n + 1))
done

# Optional dashboard router.
DASHBOARD_HOST="${DASHBOARD_HOST:-}"
DASHBOARD_AUTH="${DASHBOARD_AUTH:-}"
if [ -n "$DASHBOARD_HOST" ]; then
  {
    echo "    traefik-dashboard:"
    echo "      rule: \"Host(\`${DASHBOARD_HOST}\`)\""
    echo "      entryPoints: [websecure]"
    echo "      service: api@internal"
    echo "      tls:"
    echo "        certResolver: le"
    if [ -n "$DASHBOARD_AUTH" ]; then
      echo "      middlewares: [traefik-dashboard-auth]"
    fi
  } >> "$TMP"

  if [ -n "$DASHBOARD_AUTH" ]; then
    {
      echo "  middlewares:"
      echo "    traefik-dashboard-auth:"
      echo "      basicAuth:"
      echo "        users:"
      echo "          - \"${DASHBOARD_AUTH}\""
    } >> "$TMP"
  fi
fi

# Services section.
echo "  services:" >> "$TMP"
n=1
while :; do
  eval "name=\${ROUTE_${n}_NAME:-}"
  [ -z "$name" ] && break
  eval "service=\${ROUTE_${n}_SERVICE:-}"
  {
    echo "    ${name}:"
    echo "      loadBalancer:"
    echo "        servers:"
    echo "          - url: \"${service}\""
  } >> "$TMP"
  n=$((n + 1))
done

mv "$TMP" "$OUT"
echo "Wrote $OUT (${count} app route(s)${DASHBOARD_HOST:+ + dashboard})."
