#!/bin/sh
# Renders Traefik file-provider dynamic config from ROUTE_* variables in the env.
# POSIX sh (runs on Alpine/busybox). Output path is arg 1 (default /out/routes.yml).
#
# Route convention in .env (N = 1, 2, 3, ...; must be contiguous starting at 1):
#   ROUTE_1_NAME=dashboard                             # unique router/service id
#   ROUTE_1_HOSTS=dash.example.com,app.example.com     # comma-separated hostnames
#   ROUTE_1_SERVICE=http://dashboard:8080              # backend url (container or external)
#   ROUTE_1_TLS=true                                   # optional, default true
#   ROUTE_1_ENTRYPOINTS=websecure                      # optional, default websecure
#
# Optional Traefik dashboard:
#   DASHBOARD_HOST=traefik.example.com
#   DASHBOARD_AUTH=admin:$apr1$....   # htpasswd hash (from `htpasswd -nb admin secret`)

set -eu

OUT="${1:-/out/routes.yml}"
# Accumulate each section separately so the final file only contains an `http:`
# block when there's something to put in it. A bare `http:` with null children
# makes Traefik reject the whole file ("http cannot be a standalone element")
# AND drop every other route in the file-provider directory with it.
ROUTERS="$(mktemp)"
MIDDLEWARES="$(mktemp)"
SERVICES="$(mktemp)"
trap 'rm -f "$ROUTERS" "$MIDDLEWARES" "$SERVICES"' EXIT

count=0
n=1
while :; do
  eval "name=\${ROUTE_${n}_NAME:-}"
  [ -z "$name" ] && break

  eval "hosts=\${ROUTE_${n}_HOSTS:-}"
  eval "service=\${ROUTE_${n}_SERVICE:-}"
  eval "tls=\${ROUTE_${n}_TLS:-true}"
  eval "entry=\${ROUTE_${n}_ENTRYPOINTS:-websecure}"

  if [ -z "$hosts" ] || [ -z "$service" ]; then
    echo "ERROR: ROUTE_${n} ($name) is missing HOSTS or SERVICE" >&2
    exit 1
  fi

  # Build:  Host(`a`) || Host(`b`) || ...
  rule=""
  oldIFS=$IFS
  IFS=','
  for h in $hosts; do
    h=$(printf '%s' "$h" | tr -d ' ')
    [ -z "$h" ] && continue
    if [ -z "$rule" ]; then
      rule="Host(\`$h\`)"
    else
      rule="$rule || Host(\`$h\`)"
    fi
  done
  IFS=$oldIFS

  {
    echo "    ${name}:"
    echo "      rule: \"${rule}\""
    echo "      entryPoints: [${entry}]"
    echo "      service: ${name}"
    if [ "$tls" = "true" ]; then
      echo "      tls:"
      echo "        certResolver: le"
    fi
  } >> "$ROUTERS"

  {
    echo "    ${name}:"
    echo "      loadBalancer:"
    echo "        servers:"
    echo "          - url: \"${service}\""
  } >> "$SERVICES"

  count=$((count + 1))
  n=$((n + 1))
done

# Optional dashboard router (its service is api@internal — no services entry).
DASHBOARD_HOST="${DASHBOARD_HOST:-}"
DASHBOARD_AUTH="${DASHBOARD_AUTH:-}"
if [ -n "$DASHBOARD_HOST" ]; then
  {
    echo "    traefik-dashboard:"
    echo "      rule: \"Host(\`${DASHBOARD_HOST}\`)\""
    echo "      entryPoints: [websecure]"
    echo "      service: api@internal"
    echo "      tls:"
    echo "        certResolver: le"
    if [ -n "$DASHBOARD_AUTH" ]; then
      echo "      middlewares: [traefik-dashboard-auth]"
    fi
  } >> "$ROUTERS"

  if [ -n "$DASHBOARD_AUTH" ]; then
    {
      echo "    traefik-dashboard-auth:"
      echo "      basicAuth:"
      echo "        users:"
      echo "          - \"${DASHBOARD_AUTH}\""
    } >> "$MIDDLEWARES"
  fi
fi

# Assemble. Emit `http:` and each sub-section ONLY when non-empty; when there are
# no ROUTE_* entries and no dashboard the file is comment-only, which Traefik
# loads as an empty (valid) config instead of erroring.
{
  echo "# AUTO-GENERATED by scripts/generate-routes.sh — DO NOT EDIT BY HAND."
  echo "# Edit ../.env and re-run:  docker compose run --rm route-generator"
  if [ -s "$ROUTERS" ] || [ -s "$MIDDLEWARES" ] || [ -s "$SERVICES" ]; then
    echo "http:"
    if [ -s "$ROUTERS" ]; then
      echo "  routers:"
      cat "$ROUTERS"
    fi
    if [ -s "$MIDDLEWARES" ]; then
      echo "  middlewares:"
      cat "$MIDDLEWARES"
    fi
    if [ -s "$SERVICES" ]; then
      echo "  services:"
      cat "$SERVICES"
    fi
  fi
} > "$OUT"

echo "Wrote $OUT (${count} app route(s)${DASHBOARD_HOST:+ + dashboard})."
